- .github/CODEOWNERS
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
> Admin stuff for public visibility change

- .github/workflows/ci.yml
- .github/workflows/release.yml
> fix: fix release workflow definition

- kusogaki_bot/cogs/reminders.py
- pyproject.toml
I had some of these comments when I was writing the code to keep track of things. Forgot to remove them when code was pushed up
> Some cleanup

- kusogaki_bot/cogs/poll.py
- kusogaki_bot/cogs/reminders.py
- kusogaki_bot/data/reminder_repository.py
- kusogaki_bot/services/poll_service.py
- kusogaki_bot/services/reminder_service.py
Wanting to move towards structuring the project based on best practices:
- Cogs will fous soley on Discord-specific functionality
- Business logic for poll and reminder classes moved into service classes
- Data persistence layer for handling json related to reminders
> refactor: restructure reminder and poll cogs for maintainability

- kusogaki_bot/cogs/gta_quiz.py
- kusogaki_bot/models/game_config.py
- kusogaki_bot/models/game_state.py
- kusogaki_bot/models/round_data.py
- kusogaki_bot/services/anilist_service.py
- kusogaki_bot/services/game_message_service.py
- kusogaki_bot/services/gta_quiz_service.py
we wanted to include a GTA style quiz game similar to black tea
> feat: add gta quiz game

- README.md
> docs: add basic readme content

- docs/CONTRIBUTING.md
> Updating contributing guidelines files

- .github/dependabot.yml
- .github/workflows/deploy.yml
> ci: add deploy workflow for fly.io

- config.py
- kusogaki_bot/cogs/general.py
- kusogaki_bot/cogs/gta_quiz.py
- kusogaki_bot/cogs/poll.py
- kusogaki_bot/cogs/reminders.py
- kusogaki_bot/utils/base_cog.py
- kusogaki_bot/utils/permissions.py
> feat: add permissions model for cogs

- scripts/ruff.py
> style: update ruff script to align with poetry config

- config.py
- kusogaki_bot/cogs/reminders.py
- kusogaki_bot/services/game_message_service.py
- kusogaki_bot/utils/base_cog.py
- kusogaki_bot/utils/embeds.py
- scripts/ruff.py
> feat: add shared embed utility class

- README.md
> docs: add current commands to readme

- README.md
- kusogaki_bot/cogs/scheduled_threads.py
- kusogaki_bot/data/scheduled_thread_repository.py
- kusogaki_bot/services/scheduled_thread_service.py
> feat: add scheduled tasks

- .github/workflows/ci.yml
- .github/workflows/release.yml
> build: add release workflow

- kusogaki_bot/cogs/general.py
> feat: add cheat ping command

- .github/CODEOWNERS
> chore: update codeowners to be approvers group

- .github/workflows/ci-failure.yml
> ci: make ci failure message more explicit

- .github/workflows/ci-failure.yml
> fix: remove import from ci failure workflow

- pyproject.toml
- ruff.toml
- uv.lock
> refactor: move ruff config into ruff.toml file

- kusogaki_bot/features/miku/cog.py
Miku is now inside our bot
Checked if Miku was spying correctly.
N/A
> feat: added Miku

- kusogaki_bot/features/guess_the_anime/cog.py
> style: add spacing to countdown embed
